# Setup
title:               Nicholas Cerny
tagline:             'Violinist'
description:         'Nicholas Cerny&#39s website.'
url:                 https://nicholascerny.co.uk
baseurl:             ''
paginate:            5
paginate_path: "/page:num/"
permalink:           pretty
future: true

# About/contact
author:
  name:              Nicholas Cerny
  url:               https://nicholascerny.co.uk
  email:             nicholas.cerny1@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
